# Generated by Django 3.0.2 on 2020-05-21 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200515_0614'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_client',
            new_name='is_student',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
    ]
